name: ble_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# add pub dev 
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #*autoroute 
  auto_route: ^4.0.1
  #*Hive
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  #*Hive path
  path_provider: ^2.0.11

  #*State Management [Provider]
  provider: ^6.0.3

  #* Flutter SVG
  flutter_svg: ^1.1.0
  #* Date Time for flutter get Date 
  intl: ^0.17.0
  #* Flutter slideable 
  flutter_slidable: ^1.3.0
  #* Flutter switch toggle stype ios 
  flutter_switch: ^0.3.2
  #* Flutter bottom navbar solomon 
  salomon_bottom_bar: ^3.3.1

  #? flutter ble lib
  flutter_reactive_ble: ^5.0.2

  #! functional data to connect ble
  functional_data: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  #!autoroute [dev tools]
  auto_route_generator: ^4.0.0
  #!hive [dev tools]
  hive_generator: ^1.1.3
  #! autoroute & hive [dev tools]
  build_runner: ^2.1.11

  #! functional_data add on build
  functional_data_generator: ^1.1.4

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/icons/
    - assets/images/backgrounds/
    - assets/images/icons/icon_png/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit/Kanit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Kanit/Kanit-Italic.ttf
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
